version: '3'

services:
  server:
    build: .
    command: sh -c 'npm install; npm run seed:db; npm start'
    depends_on:
      - 'database'
    ports:
      - '3004:3004'

  database:
    image: mongo:latest
